apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: myapp-1
spec:
  build:
      useBuildKit: true
      useBuildCache: true
  environments:
  - name: dev
    build:
      from: main
  components:
  - name: server
    readOnlyFileSystem: true
    ports:
      - name: http
        port: 8080
      - name: metrics
        port: 1234
    publicPort: "http"
    src: ./server
    dockerfileName: Dockerfile.legacy
    monitoring: true
    monitoringConfig:
      portName: metrics
    authentication:
      oauth2:
        clientID: 7ef841f8-a263-45ea-8993-683cc6817ae2