# yaml-language-server: $schema=https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app
spec:
  build:
    useBuildKit: true
    useBuildCache: true
  environments:
  - name: dev
    build:
      from: main
  - name: qa
    build:
      from: main
  - name: prod
    build:
      from: release
  components:
  - name: server
    readOnlyFileSystem: true
    src: ./server
    dockerfileName: Dockerfile
    environmentConfig:
      - environment: qa
        image: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
      - environment: prod
        image: nginxinc/nginx-unprivileged:alpine3.18-perl
  - name: server2
    readOnlyFileSystem: true
    src: ./server2
    dockerfileName: Dockerfile
    environmentConfig:
      - environment: qa
        src: ./server
        dockerfileName: Dockerfile2
      - environment: prod
        image: nginxinc/nginx-unprivileged:alpine3.18-perl
  - name: server3
    readOnlyFileSystem: true
    src: ./
    dockerfileName: Dockerfile
    environmentConfig:
      - environment: qa
        image: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
      - environment: prod
        image: nginxinc/nginx-unprivileged:alpine3.18-perl
  - name: server4
    readOnlyFileSystem: true
    image: nginxinc/nginx-unprivileged:{imageTagName}
    environmentConfig:
      - environment: dev
        imageTagName: alpine-perl
      - environment: qa
        src: ./server
        dockerfileName: Dockerfile2
      - environment: prod
        imageTagName: alpine3.18-perl
