apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: myapp-9
spec:
  build:
      useBuildKit: true
      useBuildCache: true
  environments:
  - name: dev
    build:
      from: main
  dnsAlias:
  - alias: myapp-abcdef123
    environment: dev
    component: server
  components:
  - name: server
    readOnlyFileSystem: true
    ports:
      - name: http
        port: 8080
    publicPort: "http"
    src: ./server
    dockerfileName: Dockerfile.legacy
