apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app
spec:
  build:
    variables:
      VAR1: val1
  environments:
    - name: dev
      build:
        from: main
        variables:
          VAR1: val1dev
          VAR2: val2
    - name: prod
      build:
        from: release
        variables:
          VAR3: val3
  components:
    - name: server
      image: nginxinc/nginx-unprivileged
      ports:
        - name: http
          port: 8080
      publicPort: http
      ingressConfiguration:
        - leastconnectedlb
