apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: myapp-9
spec:
  build:
      useBuildKit: true
      useBuildCache: true
      secrets:
      - A
      subPipeline:
        variables:
          VAR1: value1
          VAR2: value2
  environments:
  - name: dev
    build:
      from: main
  - name: prod2
  dnsAlias:
  - alias: myapp-abcdef
    environment: dev
    component: server
  components:
  - name: server
    readOnlyFileSystem: true
    ports:
      - name: http
        port: 8080
    publicPort: "http"
    src: ./server
    dockerfileName: Dockerfile.legacy
