apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app
spec:
  build:
    useBuildKit: true
    useBuildCache: true
  environments:
    - name: dev
      build:
        from: main
    - name: dev2
      build:
        from: catalog-v*
    - name: dev3
      build:
        from: abcdddddf
  dnsAlias:
    - component: server
      environment: dev
      domain: my-app
    
  components:
    - name: server
      ports:
        - name: http
          port: 8080
      publicPort: http
      authentication:
        oauth2:
          clientId: 7ef841f8-a263-45ea-8993-683cc6817ae2
      secrets:
        - SECRET1
  dnsExternalAlias:
    - alias: radix-test.equinor.com
      environment: dev2 
      component: server

