apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app2
spec:
  build:
    useBuildKit: true
    useBuildCache: true
  environments:
    - name: dev
      build:
        from: main
    - name: dev2
      build:
        from: main
  dnsAlias:
    - alias: server2-radix-mini-app2-dev2
      component: server
      environment: dev
    - alias: myapp1-2
      component: server2
      environment: dev
    - alias: myapp2-1
      component: server
      environment: dev2
    - alias: myapp2-2
      component: server2
      environment: dev2
  components:
    - name: server
      ports:
        - name: http1
          port: 8081
      publicPort: http1
      authentication:
        oauth2:
          clientId: 7ef841f8-a263-45ea-8993-683cc6817ae2
      environmentConfig:
        - environment: dev
          enabled: true
        - environment: dev2
          enabled: true
    - name: server2
      ports:
        - name: http1
          port: 8080
      publicPort: http1
      authentication:
        oauth2:
          clientId: 7ef841f8-a263-45ea-8993-683cc6817ae2

