apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app-deploy-only
spec:
  environments:
    - name: dev
  components:
    - name: server
      readOnlyFileSystem: true
      image: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
      ports:
        - name: http
          port: 8080
