# yaml-language-server: $schema=https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app
spec:
  build:
#    useBuildKit: true
#    useBuildCache: true
  environments:
  - name: dev
    build:
      from: main
  - name: dev2
    build:
      from: main
  - name: dev3
    build:
      from: release
  - name: dev4
  dnsAlias:
    - alias: myapp321
      component: server
      environment: dev2
  dnsExternalAlias:
    - alias: myapp321.equinor.com
      component: server2
      environment: dev
  components:
  - name: server
    ports:
      - name: http
        port: 8080
    publicPort: http
    image: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
  - name: server2
    ports:
      - name: http
        port: 8080
    publicPort: http
    image: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
    # src: ./server2
    # dockerfileName: Dockerfile.legacy
