apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: myapp-1
spec:
  build:
      useBuildKit: true
      useBuildCache: true
  environments:
  - name: dev
    build:
      from: main
  components:
  - name: server
    readOnlyFileSystem: true
    ports:
      - name: http
        port: 8080
      - name: metrics
        port: 1234
    src: ./server
    dockerfileName: Dockerfile.legacy
    monitoringConfig:
      portName: metrics
      path: /my-metrics