# yaml-language-server: $schema=https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app
spec:
  build:
    useBuildKit: true
    useBuildCache: true
  environments:
  - name: dev
    build:
      from: *
  - name: dev2
    build:
      from: *
  components:
  - name: server
    readOnlyFileSystem: true
    ports:
      - name: http
        port: 8080
    src: server
