
# yaml-language-server: $schema=https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app
spec:
  build:
    variables:
      VAR1: val1
  environments:
  - name: dev
    build:
      from: main
      variables:
        VAR1: val1dev
        VAR2: val2
  - name: prod
    build:
      from: release
      variables:
        VAR3: val3
  components:
  - name: server
    readOnlyFileSystem: true
    image: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
    #      ports:
    #        - name: http
    #          port: 8080
    #      publicPort: http
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 200Mi
        cpu: 200m
    secrets:
    - A
    variables:
      B: aaa
      C: aa
  #      authentication:
  #        oauth2:
  #          clientId: 7ef841f8-a263-45ea-8993-683cc6817ae2
  - name: server2
    readOnlyFileSystem: true
    image: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
  - name: server3
    readOnlyFileSystem: true
    image: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 200Mi
        cpu: 200m
  - name: server4
    readOnlyFileSystem: true
    image: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
