apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app2
spec:
  build:
    useBuildKit: true
    useBuildCache: true
  environments:
    - name: dev
      build:
        from: main
    - name: dev2
      build:
        from: main
  dnsAlias:
    - alias: myapp1
      component: server
      environment: dev
#    - alias: myapp2
#      component: server
#      environment: dev

  components:
    - name: server
      ports:
        - name: http
          port: 8080
      publicPort: http
      authentication:
        oauth2:
          clientId: 7ef841f8-a263-45ea-8993-683cc6817ae2

