apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        for i in {"five","four","three","two","one"}; do echo $i;sleep 3; done
        echo "Goodbye, see you!"