apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        for i in {"Ground Control to Major Tom","Ground Control to Major Tom",\
        "Take your protein pills and put your helmet on",\
        "(Ten)Ground Control",\
        "(Nine) to Major Tom",\
        "(Eight)",\
        "(Seven)",\
        "(Six) Commencing",\
        "(Five) countdown, engines on",\
        "(Four)",\
        "(Three)",\
        "(Two)",\
        "Check ignition",\
        "(One) and may God's love",\
        "(Lift off) be with you"}; do echo $i;sleep 2; done
        echo "Goodbye, see you!"
