apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: VAR1t
      type: string
      default:
        type: string
        stringVal: not-set2
  steps:
    - name: hello
      image: alpine
      env:
        - name: VAR11a
          value: "Val1"
        - name: VAR11b
          value: $(params.VAR1t)
      command:
        - "printenv"
