apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  tasks:
    - name: hello
      taskRef:
        name: hello
    - name: test1-task
      taskRef:
        name: test1
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbye